### ISSUE TITLE
can't install this npm package on windows 10

### ISSUE THREAD

**Issue by pastrop** [a-ignatov-parc/grunt-video-slicer#1]
[npm-debug.txt](https://github.com/a-ignatov-parc/grunt-video-slicer/files/112754/npm-debug.txt)

I am running node v0.12.0 & npm v2.5.1

Thanks!

**Comment by a-ignatov-parc** [comment]
Owner of `ffmpeg-node` lib deleted tag that i was relying on. Will update dependencies soon.

**Comment by pastrop** [comment]
Thanks!

```
  From: Anton Ignatov <notifications@github.com>
```

 To: a-ignatov-parc/grunt-video-slicer grunt-video-slicer@noreply.github.com 
Cc: pastrop pas_trop2003@yahoo.com
 Sent: Monday, February 1, 2016 1:24 PM
 Subject: Re: [grunt-video-slicer] can't install this npm package on windows 10 (#1)

Owner of ffmpeg-node lib deleted tag that i was relying on. Will update dependencies soon.—

**Comment by a-ignatov-parc** [comment]
Fixed with 6084e4dc7ad259282bbd0ad2896a70bab75efdea

**Comment by a-ignatov-parc** [comment]
Just published updated version. Sorry for late fix
